-- Trigger for logging new invoices. Assumes same log table as in previous example

DELIMITER //
CREATE TRIGGER LOGGTRIGGER AFTER INSERT ON INVOICEROW 
FOR EACH ROW BEGIN 
   INSERT INTO INVOICEROWLOG(OPERATION,USERNAME,PRODUCT,OPTIME) 
      VALUES("INS",USER(),NEW.PRODUCTNAME,NOW());
END;
//
DELIMITER ;
