CREATE VIEW CUSTOMERINVOICE AS 
   SELECT CUSTOMER.CUSTNO,CUSTOMER.NAME,CUSTOMER.SSN,CUSTOMER.REGDATE,INVOICEROW.INVOICENO,INVOICEROW.DATEPAID,INVOICEROW.NUMBER,INVOICEROW.PRODUCT,INVOICEROW.COMPANY,INVOICEROW.COST 
   FROM CUSTOMER,INVOICEROW WHERE CUSTOMER.CUSTNO=INVOICEROW.CUSTNO
   
   UNION
   
   SELECT CUSTOMER.CUSTNO,CUSTOMER.NAME,CUSTOMER.SSN,CUSTOMER.REGDATE,PAIDINVOICEROW.INVOICENO,PAIDINVOICEROW.DATEPAID,PAIDINVOICEROW.NUMBER,PAIDINVOICEROW.PRODUCT,PAIDINVOICEROW.COMPANY,PAIDINVOICEROW.COST 
   FROM CUSTOMER,PAIDINVOICEROW WHERE CUSTOMER.CUSTNO=PAIDINVOICEROW.CUSTNO;
   