-- INDEX FOR QUERY SELECT * FROM INVOICEROW WHERE CUSTNO="XXX"; 
			
CREATE INDEX CUSTOMERINVOICES ON INVOICEROW(CUSTNO ASC) USING BTREE;
			
-- INDEX FOR QUERY SELECT * FROM CUSTOMER ORDER BY NAME; 
			
CREATE INDEX CUSTOMERNAMES ON CUSTOMER(NAME ASC) USING BTREE;
			