DROP DATABASE a00leifo;
CREATE DATABASE a00leifo;
USE a00leifo;

CREATE TABLE CUSTOMER(
	CUSTNO      CHAR(6) NOT NULL,
	SSN         CHAR(11) UNIQUE NOT NULL,
	NAME        VARCHAR(30) NOT NULL,
	REGDATE     DATETIME,
	PASSW       VARCHAR(12),
	CHECK       (SSN LIKE '[0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'),
	PRIMARY KEY (CUSTNO)
) ENGINE=INNODB;

CREATE TABLE COMPANY(
		COMPANYCODE	SMALLINT NOT NULL,
		COMPANYNAME	VARCHAR(30) NOT NULL,
		PRIMARY KEY(COMPANYCODE)
) ENGINE=INNODB;

CREATE TABLE PRODUCT(
		PRODUCTCODE	SMALLINT NOT NULL,
		PRODUCTNAME	VARCHAR(30) NOT NULL,
		PRIMARY KEY(PRODUCTCODE)
) ENGINE=INNODB;

CREATE TABLE INVOICEROW(
	CUSTNO      CHAR(6) NOT NULL,
	INVOICENO   INTEGER NOT NULL,
	DATEPAID    DATETIME,
	NUMBER      INTEGER NOT NULL,
	PRODUCT     SMALLINT NOT NULL,
	COMPANY     SMALLINT NOT NULL,
	COST        REAL NOT NULL, 
	CHECK       (COST>0),
	PRIMARY KEY (INVOICENO,NUMBER),
	FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
	FOREIGN KEY (COMPANY) REFERENCES COMPANY(COMPANYCODE),
	FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(PRODUCTCODE)

) ENGINE=INNODB;

CREATE TABLE PAIDINVOICEROW(
	CUSTNO      CHAR(6) NOT NULL,
	INVOICENO   INTEGER NOT NULL,
	DATEPAID    DATETIME,
	NUMBER      INTEGER NOT NULL,
	PRODUCT     SMALLINT NOT NULL,
	COMPANY     SMALLINT NOT NULL,
	COST        REAL NOT NULL, 
	CHECK       (COST>0),
	PRIMARY KEY (INVOICENO,NUMBER),
	FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
	FOREIGN KEY (COMPANY) REFERENCES COMPANY(COMPANYCODE),
	FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(PRODUCTCODE)

) ENGINE=INNODB;

CREATE TABLE INVOICEROWCOMMENT(
	COMMENT     VARCHAR(1024) NOT NULL,
	INVOICENO   INTEGER NOT NULL,
	NUMBER      INTEGER NOT NULL,	
	PRIMARY KEY (INVOICENO,NUMBER)
);

INSERT INTO COMPANY(COMPANYNAME,COMPANYCODE) VALUES("Skruv AB i Grums","777");
INSERT INTO COMPANY(COMPANYNAME,COMPANYCODE) VALUES("Skruv HB i Sveg","888");

INSERT INTO PRODUCT(PRODUCTCODE,PRODUCTNAME) VALUES ("01","Skruv");
INSERT INTO PRODUCT(PRODUCTCODE,PRODUCTNAME) VALUES ("02","Fl&auml;ns");
INSERT INTO PRODUCT(PRODUCTCODE,PRODUCTNAME) VALUES ("03","K&ouml;rg");

INSERT INTO CUSTOMER(CUSTNO,SSN,NAME,REGDATE) VALUES("0001","0123456","Sven P Karlsson","2016-01-01");
INSERT INTO CUSTOMER(CUSTNO,SSN,NAME,REGDATE) VALUES("0002","0123455","Greger F Numisma","2016-01-03 08:17");
INSERT INTO CUSTOMER(CUSTNO,SSN,NAME,REGDATE) VALUES("0003","0123457","Egon K Kirgisniemi","2016-01-05 08:17");

INSERT INTO INVOICEROW(CUSTNO,INVOICENO,NUMBER,PRODUCT,COMPANY,COST) VALUES ("0001","1","20","01","777",500);
INSERT INTO INVOICEROW(CUSTNO,INVOICENO,NUMBER,PRODUCT,COMPANY,COST) VALUES ("0002","2","20","01","777",200);
INSERT INTO INVOICEROW(CUSTNO,INVOICENO,NUMBER,PRODUCT,COMPANY,COST) VALUES ("0002","2","21","03","888",100);

INSERT INTO PAIDINVOICEROW(CUSTNO,INVOICENO,NUMBER,PRODUCT,COMPANY,COST) VALUES ("0003","3","22","03","888",140);
INSERT INTO PAIDINVOICEROW(CUSTNO,INVOICENO,NUMBER,PRODUCT,COMPANY,COST) VALUES ("0003","3","23","03","888",110);