CREATE TABLE INVOICEROWLOG(
    ID           INTEGER NOT NULL AUTO_INCREMENT,
    OPERATION    CHAR(3),
    USERNAME     VARCHAR(32),
    PRODUCT      SMALLINT,
    OPTIME       DATETIME,
    PRIMARY KEY(ID)
);

-- Update cost for certain invoice and row number. Makes sure Cost is positive

DELIMITER //

CREATE PROCEDURE GETCOSTPROD(prod VARCHAR(30))
BEGIN

  INSERT INTO INVOICEROWLOG(OPERATION,USERNAME,PRODUCT,OPTIME) VALUES ("SEL",USER(),prod,NOW());

  SELECT SUM(COST)
  FROM INVOICEROW
  WHERE PRODUCT=prod;

END;
//

DELIMITER ;

-- Execute procedure
CALL GETCOSTPROD('2');
