
-- Create new Customer with password

DELIMITER //

CREATE PROCEDURE CREATECUSTOMER(INCUSTNO CHAR(6),INSSN CHAR(11),INNAME VARCHAR(30),INREGDATE DATETIME,INPASSW VARCHAR(12))
BEGIN
		
		DECLARE encryptedpassword VARCHAR(12);

		encryptedpassword=LEFT(PASSWORD(INPASSW),12);
		
		INSERT INTO CUSTOMER(CUSTNO,SSN,NAME,REGDATE) VALUES (INCUSTNO,INSSN,INNAME,INREGDATE,encryptedpassword);

END;
//

DELIMITER ;

-- Create new Customer with login

DELIMITER //

CREATE PROCEDURE CHECKCUSTOMER(INCUSTNO CHAR(6),INPASSW VARCHAR(12))
BEGIN
		
		DECLARE encryptedpassword VARCHAR(12);

		encryptedpassword=LEFT(PASSWORD(INPASSW),12);
		
		IF((SELECT COUNT(*) FROM CUSTOMER WHERE CUSTNO=INCUSTNO and PASSW=encryptedpassword)>0) THEN
				SELECT 'OK' as RESULT;
		END IF;

END;
//

DELIMITER ;
